---
- hosts: nomad_instances
  become: yes

  vars:
    volume: /dev/disk/by-id/scsi-0DO_Volume_consul-data
    mount_volume: "{{ ansible_hostname == 'nomad1' and ansible_system_vendor == 'DigitalOcean' }}"
    data_dir: "{{ mount_volume | ternary('/data', '/var/consul') }}"

  pre_tasks:

  - name: Disable Firewall
    service: name=ufw state=stopped

  - name: Install HTTPS Apt Packages
    apt: name={{ item }} update_cache=yes
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  - name: Add Docker GPG Key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

  - name: Add Docker Repository
    apt_repository:
      repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state=present

  - name: Install Docker CE
    apt: name=docker-ce state=present update_cache=yes

  - name: Enable Docker at Startup
    service: name=docker state=started enabled=yes

  - name: add user mod to docker
    command: usermod -aG docker {{ ansible_user }}

  - name: Install pip
    apt: name=python-pip

  - name: Install Python Packages
    pip: name={{ item }}
    with_items:
    - docker-py

  - name: Pull Docker Python Image
    docker_image: name=python tag=2.7.13

  - name: Create Volume Filesystem
    filesystem: fstype=xfs dev={{ volume }}
    when: mount_volume

  - name: Mount Volume
    mount: path={{ data_dir }} src={{ volume }} fstype=xfs state=mounted
    when: mount_volume

  roles:

    - role: brianshumate.consul
      consul_client_address: 0.0.0.0
      consul_data_path: "{{ data_dir }}"

    - role: brianshumate.nomad
      nomad_bind_address: 0.0.0.0
      nomad_docker_enable: yes